#!/usr/bin/env bash

grim -o $(swaymsg -t get_outputs \
	| jq -r '.[] | select(.focused) | .name') - \
	| satty --disable-notifications \
	-f - -o ~/Pictures/Screenshots/$(date '+%Y%m%d-%H:%M:%S').png
