# set $PATH
typeset -U path
path=(
	/home/gsx/.local/bin
	/home/gsx/.go/bin
	/usr/local/bin
	/usr/bin/core_perl
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	$path
)

# set $MANPATH
typeset -U path
manpath=(
	/home/gsx/.local/share/man
	$manpath
)

# set pager, editor, visual and browser variables
PAGER=/usr/bin/less; export PAGER
EDITOR=/usr/bin/vi; export EDITOR
VISUAL=/usr/bin/vi; export VISUAL
BROWSER=/usr/bin/firefox; export BROWSER

# eport the hostname env variable
export HOST

# set $GOPATH
GOPATH=~/.go; export GOPATH
# reduce data send to google
# from https://git.sr.ht/~sircmpwn/dotfiles/tree/master/item/.profile
GOPROXY=direct; export GOPROXY
GOSUMDB=off; export GOSUMDB
GOTELEMETRY=off; export GOTELEMETRY

# set to avoid empty windows in java applications
_JAVA_AWT_WM_NONREPARENTING=1; export _JAVA_AWT_WM_NONREPARENTING

# dracula theme for fzf
FZF_DEFAULT_OPTS=" \
	--color=fg:#f8f8f2,hl:#bd93f9 \
	--color=fg+:#f8f8f2,bg+:#44475a,hl+:#00fa3f \
	--color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 \
	--color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4"
export FZF_DEFAULT_OPTS

