# Source the Environment

# fzf settings
# autocompletion
[[ $- == *i* ]] &&
source /usr/share/fzf/completion.zsh 2> /dev/null
# key-bindings
[[ -s /usr/share/fzf/key-bindings.zsh ]] &&
source /usr/share/fzf/key-bindings.zsh
# use fd instead of find
[[ -x $(which fd) ]] &&
FZF_DEFAULT_COMMAND='fd --type f'; export FZF_DEFAULT_COMMAND

# zsh autosuggestions
[[ -s /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] &&
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh syntax highlighting
[[ -s /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh ]] &&
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Nobody need flow control anymore. Troublesome feature.
setopt noflowcontrol

# Fix for tmux on linux.
case "$(uname -o)" in
    'GNU/Linux')
        export EVENT_NOEPOLL=1
    ;;
esac

# Aliases and Functions

# don't store su in history
alias su=' su'

# allow user to shutdown
alias halt='sudo halt'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'

# run some monitoring tools as root
hddtemp() {
	command sudo hddtemp "$@"
}

# ls aliases
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias llh="ll -h"

# mosh connections to my uberspace webspaces
alias uber-gsx='mosh -p 41400 gsx'
alias uber-gsxcloud='mosh -p 41240 gsxcloud'

# get help from cht.sh
cht() {
	command curl https://cht.sh/"$@" | less -R
}

# read Xresources before starting nsxiv
nsxiv() {
	xrdb ~/.Xresources && command nsxiv "$@"
}

# cal start week with mondays
cal() {
	khal calendar "$@"
}
# gcal
gcal() {
	command gcal --iso-week-number=yes -s1 -qDE_BY -H '\e[32m:\e[0m:\e[34m:\e[0m' "$@"
}

# don't show the banner for ffmpeg stuff
ffmpeg() {
	command ffmpeg -hide_banner "$@"
}
ffplay() {
	command ffplay -hide_banner "$@"
}
ffprobe() {
	command ffprobe -hide_banner "$@"
}
