[tasks.alacritty]
	# templates = [
	links = [
		[".config/alacritty/alacritty.toml", "alacritty/home/alacritty.toml"],
	]

[tasks.bspwm]
	links = [
		[".config/bspwm/bspwmrc", "bspwm/home/bspwmrc"],
		[".config/sxhkd/sxhkdrc", "sxhkd/sxhkdrc"],
		[".config/sxhkd/bspwm_sxhkdrc", "sxhkd/bspwm_sxhkdrc"],
	]

[tasks.chromium]
	links = [
		[".config/chromium-flags.conf", "chromium/chromium-flags.conf"],
	]

[tasks.console]
	templates = [
		["/etc/vconsole.conf", "console/vconsole.conf"],
	]

[tasks.contacts]
	links = [
		[".config/vdirsyncer/config", "vdirsyncer/config"],
		[".config/vdirsyncer/get_url.sh", "vdirsyncer/get_url.sh"],
		[".config/vdirsyncer/get_user.sh", "vdirsyncer/get_user.sh"],
		[".config/vdirsyncer/get_pass.sh", "vdirsyncer/get_pass.sh"],
		[".config/khal/config", "khal/config"],
		[".config/khard/khard.conf", "khard/khard.conf"],
	]

[tasks.Disable_ECC]
	templates = [
		["/etc/modprobe.d/edac-blacklist.conf", "Disable_ECC/edac-blacklist.conf"],
	]

[tasks.Disable_ME]
	templates = [
		["/etc/modprobe.d/mei-blacklist.conf", "Disable_ME/mei-blacklist.conf"],
	]

[tasks.doom]
	links = [
		[".config/doom/config.el", "emacs/doom/config.el"],
		[".config/doom/init.el", "emacs/doom/init.el"],
		[".config/doom/packages.el", "emacs/doom/packages.el"],
	]

[tasks.foot]
	links = [
		[".config/foot/foot.ini", "foot/foot.ini"],
	]

[tasks.gdb]
	links = [
		[".config/gdb/gdbearlyinit", "gdb/gdbearlyinit"],
	]

[tasks.git]
	links = [
		[".config/git/config", "git/config"],
	]

[tasks.gnupg]
	links = [
		[".gnupg/gpg.conf", "gnupg/gpg.conf"],
		[".gnupg/gpg-agent.conf", "gnupg/gpg-agent.conf"],
		[".gnupg/sshcontrol", "gnupg/sshcontrol"],
	]

[tasks.gui-libraries]
  links = [
	  [".config/gtk-3.0/settings.ini", "gtk/gtk-3.0/settings.ini"],
	  [".config/gtkrc-2.0", "gtk/gtkrc-2.0"],
	  [".config/Kvantum/kvantum.kvconfig", "qt/kvantum.kvconfig"],
	]

[tasks.helix]
	links = [
		[".config/helix/config.toml", "helix/config.toml"],
		[".config/helix/themes/gsx.toml", "helix/themes/gsx.toml"],
	]

[tasks.joplin]
	links = [
		[".config/joplin/keymap.json", "joplin/keymap.json"],
	]

[tasks.keychain]
	templates = [
		["/etc/profile.d/keychain.sh", "keychain/keychain.sh"],
	]

[tasks.locale]
	templates = [
		["/etc/locale.gen", "locale/locale.gen"],
		["/etc/locale.conf", "locale/locale.conf"],
	]

[tasks.mime]
  links = [
		[".config/mimeapps.list", "mime/mimeapps.list"],
		[".config/defaults.list", "mime/mimeapps.list"],
		[".local/share/applications/defaults.list", "mime/mimeapps.list"],
		[".local/share/dbus-1/services/org.freedesktop.FileManager1.service", "mime/org.freedesktop.FileManager1.service"],
	]

[tasks.mpv]
  links = [
		[".config/mpv/mpv.conf", "mpv/mpv.conf"],
	]

[tasks.neomutt]
	links = [
		[".config/neomutt/neomuttrc", "neomutt/neomuttrc"],
		[".config/neomutt/gsx.rc", "neomutt/gsx.rc"],
		[".config/neomutt/black-neon.rc", "neomutt/black-neon.rc"],
		[".config/neomutt/mailsignature", "neomutt/mailsignature"],
		[".local/share/applications/neomutt.desktop", "neomutt/neomutt.desktop"],
	]

[tasks.nsxiv]
	links = [
		[".config/nsxiv/exec/image-info", "nsxiv/image-info"],
		[".config/nsxiv/exec/key-handler", "nsxiv/key-handler"],
		[".config/nsxiv/exec/thumb-info", "nsxiv/thumb-info"],
		[".config/nsxiv/exec/win-title", "nsxiv/win-title"],
		[".local/share/applications/nsxiv.desktop", "nsxiv/nsxiv.desktop"],
	]

[tasks.nvim]
	links = [
		[".config/nvim/init.lua", "nvim/init.lua"],
		[".config/nvim/ftplugin", "nvim/ftplugin"],
		[".config/nvim/lua", "nvim/lua"],
		[".config/nvim/plugin", "nvim/plugin"],
		[".config/nvim/snippets", "nvim/snippets"],
	]

[tasks.pacman]
	templates = [
		["/etc/makepkg.conf", "pacman/arch/makepkg.conf"],
		["/etc/mkinitcpio.conf", "pacman/arch/mkinitcpio.conf"],
		["/etc/pacman.conf", "pacman/arch/pacman.conf"],
		["/etc/xdg/reflector/reflector.conf", "pacman/mirrorlist/reflector.conf"],
		["/etc/pacman.d/hooks/btrbk.hook", "pacman/hooks/btrbk.hook"],
		["/etc/pacman.d/hooks/refind.hook", "pacman/hooks/refind.hook"],
	]

[tasks.pam]
	templates = [
		["/etc/security/faillock.conf", "pam/faillock.conf"],
	]

[tasks.peaclock]
	links = [
		[".config/peaclock/binary.conf", "peaclock/home/binary.conf"],
		[".config/peaclock/digital.conf", "peaclock/home/digital.conf"],
	]
	
[tasks.polybar]
	links = [
		[".config/polybar/config", "polybar/home/config"],
		[".config/polybar/launch.sh", "polybar/home/launch.sh"],
	]

[tasks.ranger]
	links = [
		[".config/ranger/rc.conf", "ranger/rc.conf"],
		[".config/ranger/plugins/ranger_devicons", "ranger/ranger_devicons"],
	]

[tasks.ssh]
	templates = [
		["/etc/ssh/sshd_config", "ssh/sshd_config"],
	]

[tasks.stylua]
	links = [
		[".config/stylua/stylua.toml", "stylua/stylua.toml"],
	]

[tasks.sway]
	links = [
		[".config/sway/config", "sway/config"],
		[".config/swaylock/config", "swaylock/config"],
		[".config/swappy/config", "swappy/config"],
		[".Xresources", "X/home/Xresources"],
		[".local/launcher/firefox", "launcher-scripts/firefox"],
		[".local/launcher/htop", "launcher-scripts/htop"],
		[".local/launcher/btop", "launcher-scripts/btop"],
		[".local/launcher/bottom", "launcher-scripts/bottom"],
		[".local/launcher/neomutt", "launcher-scripts/neomutt"],
		[".local/launcher/weechat", "launcher-scripts/weechat"],
		[".local/launcher/nnn", "launcher-scripts/nnn"],
		[".local/launcher/ranger", "launcher-scripts/ranger"],
		[".local/launcher/vifm", "launcher-scripts/vifm"],
		[".local/launcher/xplr", "launcher-scripts/xplr"],
		[".local/launcher/fshot", "launcher-scripts/fshot"],
		[".local/launcher/sshot", "launcher-scripts/sshot"],
		[".local/launcher/wshot", "launcher-scripts/wshot"],
	]

[tasks.sway_global]
	templates = [
		["/etc/profile.d/wayland.sh", "sway/profile.d/wayland.sh"],
	]

[tasks.sysctl]
	templates = [
		["/etc/sysctl.d/99-disable-privileged-ports.conf", "sysctl/99-disable-privileged-ports.conf"],
	]

[tasks.systemd]
	templates = [
		["/etc/systemd/resolved.conf", "systemd/resolved.conf"],
		["/etc/systemd/timesyncd.conf", "systemd/timesyncd.conf"],
		["/etc/systemd/system/btrbk.timer", "systemd/system/btrbk.timer"],
		["/etc/systemd/system/btrbk.service", "systemd/system/btrbk.service"],
	]

[tasks.tmux]
	links = [
		[".config/tmux/tmux.conf", "tmux/home/tmux.conf"],
	]

[tasks.vifm]
	links = [
		[".config/vifm/vifmrc", "vifm/vifmrc"],
		[".config/vifm/icons.vim", "vifm/icons.vim"],
		[".config/vifm/colors", "/usr/share/vifm/colors"],
	]

[tasks.vscode]
	links = [
		[".config/code-flags.conf", "vscode/code-flags.conf"],
	]

[tasks.weechat]
	links = [
		[".config/weechat/alias.conf", "weechat/alias.conf"],
		[".config/weechat/buflist.conf", "weechat/buflist.conf"],
		[".config/weechat/charset.conf", "weechat/charset.conf"],
		[".config/weechat/exec.conf", "weechat/exec.conf"],
		[".config/weechat/fifo.conf", "weechat/fifo.conf"],
		[".config/weechat/fset.conf", "weechat/fset.conf"],
		[".config/weechat/guile.conf", "weechat/guile.conf"],
		[".config/weechat/irc.conf", "weechat/irc.conf"],
		[".config/weechat/logger.conf", "weechat/logger.conf"],
		[".config/weechat/lua.conf", "weechat/lua.conf"],
		[".config/weechat/perl.conf", "weechat/perl.conf"],
		[".config/weechat/plugins.conf", "weechat/plugins.conf"],
		[".config/weechat/python.conf", "weechat/python.conf"],
		[".config/weechat/relay.conf", "weechat/relay.conf"],
		[".config/weechat/ruby.conf", "weechat/ruby.conf"],
		[".config/weechat/script.conf", "weechat/script.conf"],
		[".config/weechat/spell.conf", "weechat/spell.conf"],
		[".config/weechat/tcl.conf", "weechat/tcl.conf"],
		[".config/weechat/trigger.conf", "weechat/trigger.conf"],
		[".config/weechat/typing.conf", "weechat/typing.conf"],
		[".config/weechat/weechat.conf", "weechat/weechat.conf"],
		[".config/weechat/xfer.conf", "weechat/xfer.conf"],
	]

[tasks.wezterm]
	links = [
		[".config/wezterm/wezterm.lua", "wezterm/wezterm.lua"],
		[".config/wezterm/dracula.lua", "wezterm/dracula.lua"],
	]

[tasks.X]
	links = [
		[".Xresources", "X/home/Xresources"],
		[".xinitrc", "X/home/xinitrc"],
		[".xsession", "X/home/xsession"],
	]

[tasks.X_global]
	templates = [
		["/etc/X11/xorg.conf.d/10-evdev.conf", "etc/xorg.conf.d/10-evdev.conf"],
		["/etc/X11/xorg.conf.d/20-security.conf", "etc/xorg.conf.d/20-security.conf"],
	]

[tasks.xplr]
	links = [
		[".config/xplr/init.lua", "xplr/init.lua"],
	]

[tasks.yay]
	links = [
		[".config/yay/config.json", "yay/config.json"],
	]

[tasks.zathura]
	links = [
		[".config/zathura/zathurarc", "zathura/zathurarc"],
	]

[tasks.zsh]
	links = [
		[".config/zsh/.zshenv", "zsh/home/zshenv"],
		[".config/zsh/zshenv", "zsh/home/zshenv"],
		[".config/zsh/.zshrc", "zsh/home/zshrc"],
		[".config/zsh/zshrc", "zsh/home/zshrc"],
		[".config/zsh/.zprofile", "zsh/home/zprofile"],
		[".config/zsh/zprofile", "zsh/home/zprofile"],
		[".config/zsh/.zlogin", "zsh/home/zlogin"],
		[".config/zsh/zlogin", "zsh/home/zlogin"],
		[".config/zsh/.zlogout", "zsh/home/zlogout"],
		[".config/zsh/zlogout", "zsh/home/zlogout"],
	]

[tasks.zsh_global]
	templates = [
		["/etc/zsh/zshenv", "zsh/etc/zshenv"],
		["/etc/zsh/zshrc", "zsh/etc/zshrc"],
		["/etc/zsh/zprofile", "zsh/etc/zprofile"],
		["/etc/zsh/zlogin", "zsh/etc/zlogin"],
		["/etc/zsh/zlogout", "zsh/etc/zlogout"],
		["/etc/zsh/read_terminfo.zsh", "zsh/etc/read_terminfo.zsh"],
	]
