[tasks.alacritty]
	links = [
		[".config/alacritty/alacritty.yml", "alacritty/home/alacritty.yml"],
	]

[tasks.bspwm]
	links = [
		[".config/bspwm/bspwmrc", "bspwm/home/bspwmrc"],
	]

[tasks.Disable_ECC]
	links = [
		["/etc/modprobe.d/edac-blacklist.conf", "Disable_ECC/edac-blacklist.conf"],
	]

[tasks.neomutt]
	links = [
		[".config/neomutt/neomuttrc", "neomutt/home/neomuttrc"],
		[".config/neomutt/mailsignature", "neomutt/home/mailsignature"],
	]

[tasks.nvim]
	links = [
		[".config/nvim/init.vim", "nvim/home/init.vim"],
		[".config/nvim/config", "nvim/home/config"],
		[".config/nvim/ftplugin", "nvim/home/ftplugin"],
		[".config/nvim/lua", "nvim/home/lua"],
		[".config/nvim/snippets", "nvim/home/snippets"],
	]

[tasks.peaclock]
	links = [
		[".config/peaclock/binary.conf", "peaclock/home/binary.conf"],
		[".config/peaclock/digital.conf", "peaclock/home/digital.conf"],
	]
	
[tasks.polybar]
	links = [
		[".config/polybar/config", "polybar/home/config"],
		[".config/polybar/launch.sh", "polybar/home/launch.sh"],
	]

[tasks.ranger]
	links = [
		[".config/ranger/rc.conf", "ranger/home/rc.conf"],
	]

[tasks.tmux]
	links = [
		[".config/tmux/tmux.conf", "tmux/home/tmux.conf"],
	]

[tasks.vdirsyncer]
	links = [
		[".config/vdirsyncer/config", "vdirsyncer/config"],
		[".config/vdirsyncer/get_url.sh", "vdirsyncer/get_url.sh"],
		[".config/vdirsyncer/get_user.sh", "vdirsyncer/get_user.sh"],
		[".config/vdirsyncer/get_pass.sh", "vdirsyncer/get_pass.sh"],
	]

[tasks.X]
	links = [
		[".Xresources", "X/home/Xresources"],
		[".xinitrc", "X/home/xinitrc"],
		[".xsession", "X/home/xsession"],
	]

[tasks.X_global]
	links = [
		["/etc/X11/xorg.conf.d/10-evdev.conf", "etc/xorg.conf.d/10-evdev.conf"],
		["/etc/X11/xorg.conf.d/20-security.conf", "etc/xorg.conf.d/20-security.conf"],
	]

[tasks.yay]
	links = [
		[".config/yay/config.json", "yay/config.json"],
	]

[tasks.zsh]
	links = [
		[".config/zsh/.zshenv", "zsh/home/zshenv"],
		[".config/zsh/zshenv", "zsh/home/zshenv"],
		[".config/zsh/.zshrc", "zsh/home/zshrc"],
		[".config/zsh/zshrc", "zsh/home/zshrc"],
		[".config/zsh/.zprofile", "zsh/home/zprofile"],
		[".config/zsh/zprofile", "zsh/home/zprofile"],
		[".config/zsh/.zlogin", "zsh/home/zlogin"],
		[".config/zsh/zlogin", "zsh/home/zlogin"],
		[".config/zsh/.zlogout", "zsh/home/zlogout"],
		[".config/zsh/zlogout", "zsh/home/zlogout"],
		[".config/zsh/plugins", "zsh/home/plugins/"],
	]

[tasks.zsh_global]
	links = [
		["/etc/zsh/zshenv", "zsh/etc/zshenv"],
		["/etc/zsh/zshrc", "zsh/etc/zshrc"],
		["/etc/zsh/zprofile", "zsh/etc/zprofile"],
		["/etc/zsh/zlogin", "zsh/etc/zlogin"],
		["/etc/zsh/zlogout", "zsh/etc/zlogout"],
		["/etc/zsh/grc.sh", "zsh/etc/grc.sh"],
		["/etc/zsh/read_terminfo.zsh", "zsh/etc/read_terminfo.zsh"],
	]
