[tasks.alacritty]
	links = [
		[".config/alacritty/alacritty.yml", "alacritty/home/alacritty.yml"],
	]

[tasks.bspwm]
	links = [
		[".config/bspwm/bspwmrc", "bspwm/home/bspwmrc"],
	]

[tasks.neomutt]
	links = [
		[".config/neomutt/neomuttrc", "neomutt/home/neomuttrc"],
		[".config/neomutt/mailsignature", "neomutt/home/mailsignature"],
	]

[tasks.nvim]
	links = [
		[".config/nvim/init.vim", "nvim/home/init.vim"],
		[".config/nvim/config", "nvim/home/config"],
		[".config/nvim/ftplugin", "nvim/home/ftplugin"],
		[".config/nvim/lua", "nvim/home/lua"],
	]

[tasks.polybar]
	links = [
		[".config/polybar/config", "polybar/home/config"],
		[".config/polybar/launch.sh", "polybar/home/launch.sh"],
	]

[tasks.tmux]
	links = [
		[".config/tmux/tmux.conf", "tmux/home/tmux.conf"],
	]

[tasks.zsh]
	links = [
		[".config/zsh/.zshenv", "zsh/home/zshenv"],
		[".config/zsh/zshenv", "zsh/home/zshenv"],
		[".config/zsh/.zshrc", "zsh/home/zshrc"],
		[".config/zsh/zshrc", "zsh/home/zshrc"],
		[".config/zsh/.zprofile", "zsh/home/zprofile"],
		[".config/zsh/zprofile", "zsh/home/zprofile"],
		[".config/zsh/.zlogin", "zsh/home/zlogin"],
		[".config/zsh/zlogin", "zsh/home/zlogin"],
		[".config/zsh/.zlogout", "zsh/home/zlogout"],
		[".config/zsh/zlogout", "zsh/home/zlogout"],
		[".config/zsh/plugins", "zsh/home/plugins/"],
	]

[tasks.zsh_global]
	links = [
		["/etc/zsh/zshenv", "zsh/etc/zshenv"],
		["/etc/zsh/zshrc", "zsh/etc/zshrc"],
		["/etc/zsh/zprofile", "zsh/etc/zprofile"],
		["/etc/zsh/zlogin", "zsh/etc/zlogin"],
		["/etc/zsh/zlogout", "zsh/etc/zlogout"],
		["/etc/zsh/grc.sh", "zsh/etc/grc.sh"],
		["/etc/zsh/read_terminfo.zsh", "zsh/etc/read_terminfo.zsh"],
	]
