[tasks.alacritty]
	# templates = [
	links = [
		[".config/alacritty/alacritty.yml", "alacritty/home/alacritty.yml"],
	]

[tasks.bspwm]
	links = [
		[".config/bspwm/bspwmrc", "bspwm/home/bspwmrc"],
		[".config/sxhkd/sxhkdrc", "sxhkd/sxhkdrc"],
		[".config/sxhkd/bspwm_sxhkdrc", "sxhkd/bspwm_sxhkdrc"],
	]

[tasks.console]
	templates = [
		["/etc/vconsole.conf", "console/vconsole.conf"],
	]

[tasks.contacts]
	links = [
		[".config/vdirsyncer/config", "vdirsyncer/config"],
		[".config/vdirsyncer/get_url.sh", "vdirsyncer/get_url.sh"],
		[".config/vdirsyncer/get_user.sh", "vdirsyncer/get_user.sh"],
		[".config/vdirsyncer/get_pass.sh", "vdirsyncer/get_pass.sh"],
		[".config/khal/config", "khal/config"],
		[".config/khard/khard.conf", "khard/khard.conf"],
	]

[tasks.Disable_ECC]
	templates = [
		["/etc/modprobe.d/edac-blacklist.conf", "Disable_ECC/edac-blacklist.conf"],
	]

[tasks.git]
	links = [
		[".config/git/config", "git/config"],
	]

[tasks.gnupg]
	links = [
		[".gnupg/gpg.conf", "gnupg/gpg.conf"],
		[".gnupg/gpg-agent.conf", "gnupg/gpg-agent.conf"],
	]

[tasks.gui-libraries]
  links = [
	  [".config/gtk-3.0/settings.ini", "gtk/gtk-3.0/settings.ini"],
	  [".config/gtkrc-2.0", "gtk/gtkrc-2.0"],
	  [".config/Kvantum/kvantum.kvconfig", "qt/kvantum.kvconfig"],
	]

[tasks.helix]
	links = [
		[".config/helix/config.toml", "helix/config.toml"],
		[".config/helix/themes/dracula_transparent.toml", "helix/themes/dracula_transparent.toml"],
	]

[tasks.joplin]
	links = [
		[".config/joplin/keymap.json", "joplin/keymap.json"],
	]

[tasks.keychain]
	templates = [
		["/etc/profile.d/keychain.sh", "keychain/keychain.sh"],
	]

[tasks.locale]
	templates = [
		["/etc/locale.gen", "locale/locale.gen"],
		["/etc/locale.conf", "locale/locale.conf"],
	]

[tasks.mpv]
  links = [
		[".config/mpv/mpv.conf", "mpv/mpv.conf"],
	]

[tasks.neomutt]
	links = [
		[".config/neomutt/neomuttrc", "neomutt/neomuttrc"],
		[".config/neomutt/gsx.rc", "neomutt/gsx.rc"],
		[".config/neomutt/black-neon.rc", "neomutt/black-neon.rc"],
		[".config/neomutt/mailsignature", "neomutt/mailsignature"],
	]

[tasks.nvim]
	links = [
		[".config/nvim/init.lua", "nvim/init.lua"],
		[".config/nvim/ftplugin", "nvim/ftplugin"],
		[".config/nvim/lua", "nvim/lua"],
		[".config/nvim/snippets", "nvim/snippets"],
	]

[tasks.pacman]
	templates = [
		["/etc/makepkg.conf", "pacman/arch/makepkg.conf"],
		["/etc/mkinitcpio.conf", "pacman/arch/mkinitcpio.conf"],
		["/etc/pacman.conf", "pacman/arch/pacman.conf"],
		["/etc/xdg/reflector/reflector.conf", "pacman/mirrorlist/reflector.conf"],
		["/etc/pacman.d/hooks/btrbk.hook", "pacman/hooks/btrbk.hook"],
		["/etc/pacman.d/hooks/refind.hook", "pacman/hooks/refind.hook"],
	]

[tasks.pam]
	templates = [
		["/etc/security/faillock.conf", "pam/faillock.conf"],
	]

[tasks.peaclock]
	links = [
		[".config/peaclock/binary.conf", "peaclock/home/binary.conf"],
		[".config/peaclock/digital.conf", "peaclock/home/digital.conf"],
	]
	
[tasks.polybar]
	links = [
		[".config/polybar/config", "polybar/home/config"],
		[".config/polybar/launch.sh", "polybar/home/launch.sh"],
	]

[tasks.ranger]
	links = [
		[".config/ranger/rc.conf", "ranger/rc.conf"],
		[".config/ranger/plugins/ranger_devicons", "ranger/ranger_devicons"],
	]

[tasks.ssh]
	templates = [
		["/etc/ssh/sshd_config", "ssh/sshd_config"],
	]

[tasks.stylua]
	links = [
		[".config/stylua/stylua.toml", "stylua/stylua.toml"],
	]

[tasks.sway]
	links = [
		[".config/sway/config", "sway/config"],
		[".config/swaylock/config", "swaylock/config"],
		[".config/swappy/config", "swappy/config"],
		[".Xresources", "X/home/Xresources"],
		[".local/launcher/firefox", "launcher-scripts/firefox"],
		[".local/launcher/htop", "launcher-scripts/htop"],
		[".local/launcher/neomutt", "launcher-scripts/neomutt"],
		[".local/launcher/ranger", "launcher-scripts/ranger"],
		[".local/launcher/vifm", "launcher-scripts/vifm"],
		[".local/launcher/fshot", "launcher-scripts/fshot"],
		[".local/launcher/sshot", "launcher-scripts/sshot"],
		[".local/launcher/wshot", "launcher-scripts/wshot"],
	]

[tasks.sway_global]
	templates = [
		["/etc/profile.d/wayland.sh", "sway/profile.d/wayland.sh"],
	]

[tasks.sysctl]
	templates = [
		["/etc/sysctl.d/40-IPv6.conf", "sysctl/40-IPv6.conf"],
	]

[tasks.systemd]
	templates = [
		["/etc/systemd/resolved.conf", "systemd/resolved.conf"],
		["/etc/systemd/timesyncd.conf", "systemd/timesyncd.conf"],
		["/etc/systemd/system/btrbk.timer", "systemd/system/btrbk.timer"],
		["/etc/systemd/system/btrbk.service", "systemd/system/btrbk.service"],
	]

[tasks.tmux]
	links = [
		[".config/tmux/tmux.conf", "tmux/home/tmux.conf"],
	]

[tasks.vifm]
	links = [
		[".config/vifm/vifmrc", "vifm/vifmrc"],
		[".config/vifm/icons.vim", "vifm/icons.vim"],
		[".config/vifm/colors", "/usr/share/vifm/colors"],
	]

[tasks.X]
	links = [
		[".Xresources", "X/home/Xresources"],
		[".xinitrc", "X/home/xinitrc"],
		[".xsession", "X/home/xsession"],
	]

[tasks.X_global]
	templates = [
		["/etc/X11/xorg.conf.d/10-evdev.conf", "etc/xorg.conf.d/10-evdev.conf"],
		["/etc/X11/xorg.conf.d/20-security.conf", "etc/xorg.conf.d/20-security.conf"],
	]

[tasks.wezterm]
	links = [
		[".config/wezterm/wezterm.lua", "wezterm/wezterm.lua"],
		[".config/wezterm/dracula.lua", "wezterm/dracula.lua"],
	]

[tasks.yay]
	links = [
		[".config/yay/config.json", "yay/config.json"],
	]

[tasks.zsh]
	links = [
		[".config/zsh/.zshenv", "zsh/home/zshenv"],
		[".config/zsh/zshenv", "zsh/home/zshenv"],
		[".config/zsh/.zshrc", "zsh/home/zshrc"],
		[".config/zsh/zshrc", "zsh/home/zshrc"],
		[".config/zsh/.zprofile", "zsh/home/zprofile"],
		[".config/zsh/zprofile", "zsh/home/zprofile"],
		[".config/zsh/.zlogin", "zsh/home/zlogin"],
		[".config/zsh/zlogin", "zsh/home/zlogin"],
		[".config/zsh/.zlogout", "zsh/home/zlogout"],
		[".config/zsh/zlogout", "zsh/home/zlogout"],
	]

[tasks.zsh_global]
	templates = [
		["/etc/zsh/zshenv", "zsh/etc/zshenv"],
		["/etc/zsh/zshrc", "zsh/etc/zshrc"],
		["/etc/zsh/zprofile", "zsh/etc/zprofile"],
		["/etc/zsh/zlogin", "zsh/etc/zlogin"],
		["/etc/zsh/zlogout", "zsh/etc/zlogout"],
		["/etc/zsh/grc.sh", "zsh/etc/grc.sh"],
		["/etc/zsh/read_terminfo.zsh", "zsh/etc/read_terminfo.zsh"],
	]
