#!/usr/bin/env bash

grim -g "$(hyprctl activewindow -j \
	| jq -j '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" - \
	| satty --disable-notifications \
	-f - -o ~/Pictures/Screenshots/$(date '+%Y%m%d-%H:%M:%S').png
