theme = "gsx"

[editor]
gutters = ["diagnostics", "spacer", "diff"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
