[misc]
man_path = /etc/profiles/per-user/gsx/bin/man
groff_path = /etc/profiles/per-user/gsx/bin/groff
whatis_path = /etc/profiles/per-user/gsx/bin/whatis
apropos_path = /etc/profiles/per-user/gsx/bin/apropos
browser_path = /run/current-system/sw/bin/firefox
mailer_path = /home/gsx/.local/launcher/neomutt
viewer_path = /home/gsx/.local/launcher/vifm
