# Syntax
"type"              = { fg = "cyan", modifiers = ["italic"] }
"type.enum.variant" = { fg = "fg", modifiers   = ["italic"] }

"constant"                  = { fg = "blue" }
"constant.character.escape" = { fg = "magenta" }

"string"        = { fg = "yellow" }
"string.regexp" = { fg = "red" }

"comment" = { fg = "comment" }

"variable"           = { fg = "fg" }
"variable.builtin"   = { fg = "cyan", modifiers   = ["italic"] }
"variable.parameter" = { fg = "orange", modifiers = ["italic"] }

"punctuation" = { fg = "fg" }

"keyword" = { fg = "magenta" }

"operator" = { fg = "magenta" }

"function" = { fg = "green" }

"tag" = { fg = "magenta" }

"markup.heading"   = { fg   = "blue", modifiers = ["bold"] }
"markup.list"      = "cyan"
"markup.bold"      = { fg   = "orange", modifiers = ["bold"] }
"markup.italic"    = { fg   = "yellow", modifiers = ["italic"] }
"markup.link.url"  = "cyan"
"markup.link.text" = "magenta"
"markup.quote"     = { fg   = "yellow", modifiers = ["italic"] }
"markup.raw"       = { fg   = "fg" }

"diff.plus"  = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }

# Interface
"ui.background"           = { fg = "fg" }
"ui.background.separator" = { fg = "comment" }
"ui.cursor"               = { fg = "bg", bg      = "orange", modifiers  = ["dim"] }
"ui.cursor.primary"       = { fg = "bg", bg      = "green", modifiers   = ["dim"] }
"ui.gutter"               = { fg = "gutter_fg" }
"ui.gutter.selected"      = { fg = "fg" }
"ui.linenr"               = { fg = "gutter_fg" }
"ui.linenr.selected"      = { fg = "fg" }
"ui.statusline"           = { fg = "fg", bg      = "bglight" }
"ui.statusline.inactive"  = { fg = "comment", bg = "bgdark" }
"ui.statusline.normal"    = { fg = "bgdark", bg  = "blue", modifiers    = ["bold"] }
"ui.statusline.insert"    = { fg = "bgdark", bg  = "green", modifiers   = ["bold"] }
"ui.statusline.select"    = { fg = "bgdark", bg  = "magenta", modifiers = ["bold"] }
"ui.popup"                = { fg = "fg", bg      = "bgdark" }
"ui.window"               = { fg = "comment" }
"ui.help"                 = { fg = "fg", bg      = "bgdark" }
"ui.text"                 = { fg = "fg" }
"ui.text.focus"           = { fg = "cyan" }
"ui.virtual.ruler"        = { bg = "bgdark"}
"ui.virtual.whitespace"   = { fg = "comment" }
"ui.menu"                 = { fg = "fg", bg      = "bgdark" }
"ui.menu.selected"        = { fg = "cyan", bg    = "bgdark" }
"ui.selection"            = { bg = "bglighter" }
"ui.selection.primary"    = { bg = "bglighter" }
"ui.cursorline.primary"   = { bg = "bgdark" }
"ui.cursor.match"         = { modifiers = ["underlined"] }

# Gutter
"hint"    = { fg = "blue", modifiers   = ["bold"] }
"info"    = { fg = "green", modifiers  = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error"   = { fg = "red", modifiers    = ["bold"] }

# Diagnostics
"diagnostic.hint".underline    = { fg = "blue", style   = "curl" }
"diagnostic.info".underline    = { fg = "green", style  = "curl" }
"diagnostic.warning".underline = { fg = "yellow", style = "curl" }
"diagnostic.error".underline   = { fg = "red", style    = "curl" }

# Color Palette
[palette]
"bglighter"      = '#424450'
"bglight"        = '#343746'
"bg"             = '#181A26'
"bgdark"         = '#21222C'
"bgdarker "      = '#191A21'

"fg"             = '#F8F8F2'

"black"          = '#21222C'
"red"            = '#FF5555'
"green"          = '#00FA3F'
"yellow"         = '#BFFA35'
"blue"           = '#C153F9'
"magenta"        = '#FF24A2'
"cyan"           = '#26D7FD'
"white"          = '#BFBFBF'
"orange"         = '#FF9422'

"bright_black"   = '#3e4452'
"bright_red"     = '#FF6E67'
"bright_green"   = '#25F76B'
"bright_yellow"  = '#DAF97D'
"bright_blue"    = '#B682FA'
"bright_magenta" = '#FF5DB9'
"bright_cyan"    = '#86E9FE'
"bright_white"   = '#E6E6E6'
"bright_orange"  = '#FFB86C'

"comment"        = '#6272A4'
"selection"      = '#44475A'

"menu"           = '#21222C'
"visual"         = '#3E4452'
"gutter_fg"      = '#4B5263'
"nontext"        = '#3B4048'
