#!/bin/sh

if [ $(hostname) = pc ]; then
	bspc monitor DVI-I-1 -d 1 2 3
	bspc monitor DP-1 -d 4 5 6 7
	bspc monitor HDMI-0 -d 8 9 0  
fi

if [ $(hostname) = x230 ]; then
	bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 0 
fi

bspc config border_width        1
bspc config window_gap          0
bspc config top_padding         0
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	false
bspc config history_aware_focus  	true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus        false
bspc config adaptive raise        true

bspc config center_pseudo_tiled   true

bspc config initial_polarity second_child

bspc config normal_border_color   "#181a26"
bspc config focused_border_color  "#c153f9"
bspc config presel_feedback_color "#181a26"

bspc rule -a mpv state=floating
bspc rule -a firefox:firefox state=floating rectangle=0x0+1100+700
bspc rule -a 'Tor Browser' state=floating
bspc rule -a rofi focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a 'Double Commander:doublecmd:Options' state=floating
bspc rule -a KeePassXC desktop=''
if [ $(hostname) = pc ]; then
	bspc rule -a Ferdium desktop=''
	bspc rule -a Signal desktop=''
fi
